spring:
  config:
    import: application-secret.yaml
  application:
    name: stone-ai-exam
  datasource:
    url: jdbc:mysql://localhost:3306/stone_ai_exam?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  data:
    redis:
      host: 192.168.41.135 # 写自己的Redis所在服务器地址
      port: 6379
      password: 123456
      database: 1 # 使用DB1,可选以根据自己需要修改

  ai:
    openai:
      base-url: https://api.deepseek.com

      chat:
        options:
          model: deepseek-v4-pro
      retry:
        max-attempts: 3 # 服务降级：最大重试3次
        backoff:
          initial-interval: 2000
          multiplier: 2

server:
  port: 8080

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: full # 自动映射行为
    map-underscore-to-camel-case: true

dromara:
  x-file-storage:
    default-platform: aliyun-oss-1

jwt:
  secret: 32Znr25pR4lo+hCIn8zzRLgNImvC3+zZBWSbza5bSXw=
  expiration: 86400000 # 24小时=24*60*60*1000
